services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tg_disconnection_bot
    volumes:
      - ./app:/voe-bot/app
    restart: unless-stopped
    environment:
      - TZ=Europe/Kyiv
    env_file:
      - .env
    depends_on:
      - flaresolver
      - redis
    ports:
      - "8443:8443"

  redis:
    image: "redis:alpine"
    container_name: tg_disconnection_bot_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    env_file:
      - .env


  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    container_name: tg_disconnection_bot_flaresolver
    environment:
      - TZ=Europe/Kyiv

volumes:
  redis_data: