services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    container_name: tg_disconnection_bot
    volumes:
      - ./app:/sasalka/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Kyiv
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: tg_disconnection_bot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env


  flaresolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    container_name: tg_disconnection_bot_flaresolver
    ports:
      - "8191:8191"

volumes:
  redis_data: